name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: '16.8'
          check-latest: true
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
      - name: npm install
        run: npm i
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier:check
      - name: Typecheck
        run: npm run typecheck
      - name: Bundle
        run: |
          npm run build
          npm run build:types
      - name: Test
        run: npm t -- --coverage --colors
      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: '16.x'
          check-latest: true
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: node_modules/.cache
          key: build-${{ hashFiles('package.json') }}
      - name: Build
        run: |
          npm i
          npm run build:website
      - name: Set up git user
        if: github.event_name == 'push'
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
      - name: Deploy gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages
          cd gh-pages
          git rm -r .
          git checkout gh-pages -- old
          mv ../dist/* .
          git add .
          git commit -m "gh-pages deployment" || echo "Nothing to commit"
          git push -f https://adazzle:${{secrets.GITHUB_TOKEN}}@github.com/adazzle/react-data-grid.git
